version: '3.8'

services:
  api:
    container_name: fastapi_app
    build: .
    command: /bin/sh -c "apt update && apt install -y curl && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=1
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/api/v1/books/1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/fastapi.conf:/etc/nginx/conf.d/default.conf:ro  # Ensure this file exists
    depends_on:
      api:
        condition: service_healthy
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

