version: '3.8'

services:
  api:
    container_name: fastapi_app
    build: .  # Build from the Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=1
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/fastapi.conf:/etc/nginx/conf.d/default.conf:ro  # Updated path
    depends_on:
      - api
    restart: always

