name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/fastapi-book-project

            # Ensure system-wide Nginx is OFF
            sudo systemctl stop nginx || true
            sudo systemctl disable nginx || true

            # Pull latest code
            git reset --hard origin/main
            git pull origin main

            # Stop & Remove Old Containers
            docker-compose down || true

            # Remove old images to free space
            docker system prune -af || true

            # Rebuild & Restart Containers
            docker-compose up -d --build

            # Restart Nginx Inside Docker
            docker exec nginx nginx -s reload || true

            # Check if containers are running
            docker ps

            # Test the FastAPI endpoint internally
            docker exec fastapi_app curl -X GET "http://127.0.0.1:8000/api/v1/books/1"

            # Test the public endpoint
            curl -X GET "http://13.60.198.237/api/v1/books/1"

