name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH Key 🔑
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 🚀
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "Pulling latest code..."
            cd /home/ubuntu
            git clone https://github.com/OmachokoYakubu/fastapi-book-project.git || (cd fastapi-book-project && git pull origin main)
            cd fastapi-book-project

            echo "Building Docker image..."
            docker build -t chockqoteewy/fastapi-app .

            echo "Stopping and removing existing containers..."
            docker stop fastapi_app || true
            docker rm fastapi_app || true

            echo "Running new container..."
            docker run -d --name fastapi_app -p 8000:8000 chockqoteewy/fastapi-app

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
          EOF

